name: build

on:
  push:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      -
        run: yarn install --frozen-lockfile
      -
        run: yarn run build
      -
        if: ${{ github.event_name != 'release' }}
        run: npm publish --dry-run
      -
        if: ${{ github.event_name == 'release' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
